import Head from 'next/head'
import React from 'react'
import Header from '../components/Header'

type Props = {
  children: React.ReactNode
}

const Layout: React.FC<Props> = ({ children }) => {
  return (
    <React.Fragment>
      <Head>
        <title>Dev Exam</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main className="container mx-auto max-w-5xl py-3 px-5">{children}</main>
    </React.Fragment>
  )
}

export default Layout
